import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile } from "@/lib/auth";
import { savePortfolioItem } from "@/app/portfolio/actions";

export default async function PortfolioPage() {
  const profile = await getCurrentProfile();
  const supabase = await createClient();
  const { data: items } = await supabase.from("portfolio_items").select("id,title,description,is_public,submission_id,submissions(status)").eq("learner_id", profile.id).order("created_at", { ascending: false });
  return <main className="shell" style={{ paddingBlock: 30, display: "grid", gap: 20 }}><section><p className="eyebrow">Your evidence</p><h1>Learner portfolio</h1><p style={{ color: "var(--muted)" }}>Choose which completed work is visible publicly. Verified submissions can be presented as verified evidence.</p></section><form action={savePortfolioItem} className="card" style={{ padding: 22, display: "grid", gap: 14 }}><div className="field"><label htmlFor="title">Project title</label><input id="title" name="title" required maxLength={160} /></div><div className="field"><label htmlFor="description">Description</label><textarea id="description" name="description" rows={4} maxLength={2000} /></div><div className="field"><label htmlFor="submission_id">Verified submission</label><select id="submission_id" name="submission_id"><option value="">Independent portfolio item</option>{(items ?? []).filter((i: any) => i.submissions?.status === "verified").map((i: any) => <option key={i.submission_id} value={i.submission_id}>{i.title}</option>)}</select></div><label><input type="checkbox" name="is_public" /> Make public</label><button className="button" type="submit">Add portfolio item</button></form><section style={{ display: "grid", gap: 14 }}>{(items ?? []).map((item: any) => <article className="card" style={{ padding: 20 }} key={item.id}><h2>{item.title}</h2><p>{item.description}</p><p>{item.submissions?.status === "verified" ? "✓ Verified evidence" : "Project evidence"} · {item.is_public ? "Public" : "Private"}</p></article>)}</section></main>;
}
